package pguser

import (
	"time"
	"vexentra-api/internal/modules/user"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// userModel คือ Schema ที่ตรงกับ Table ใน Database
type userModel struct {
	ID           uuid.UUID `gorm:"type:uuid;primaryKey"`
	Username     string    `gorm:"uniqueIndex;not null"`
	Email        string    `gorm:"uniqueIndex;not null"`
	PasswordHash string    `gorm:"column:password_hash;not null"`
	DisplayName  string    `gorm:"column:display_name"`
	IsActive     bool      `gorm:"column:is_active;default:true"`
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    gorm.DeletedAt `gorm:"index"` // soft delete — GORM filters deleted rows automatically
}

func (userModel) TableName() string { return "users" }

// Mapper: แปลง DB Model -> Domain Entity
func (m *userModel) ToEntity() *user.User {
	var deletedAt *time.Time
	if m.DeletedAt.Valid {
		t := m.DeletedAt.Time
		deletedAt = &t
	}
	return &user.User{
		ID:          m.ID,
		Username:    m.Username,
		Email:       m.Email,
		Password:    m.PasswordHash,
		DisplayName: m.DisplayName,
		IsActive:    m.IsActive,
		CreatedAt:   m.CreatedAt,
		UpdatedAt:   m.UpdatedAt,
		DeletedAt:   deletedAt,
	}
}

// Mapper: แปลง Domain Entity -> DB Model (เพื่อเซฟลง DB)
func fromUserEntity(u *user.User) *userModel {
	return &userModel{
		ID:           u.ID, // UUID generated by repository before calling this
		Username:     u.Username,
		Email:        u.Email,
		PasswordHash: u.Password,
		DisplayName:  u.DisplayName,
		IsActive:     u.IsActive,
	}
}
